sudo: false
language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"

install:
    - cpanm --quiet --notest --skip-satisfied Dist::Zilla
    - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
    - dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose --notest

script:
    - dzil smoke --release --author

after_success:
    - cpanm --quiet --notest --skip-satisfied Dist::Zilla::App::Command::cover Devel::Cover::Report::Coveralls
    - dzil cover -test
    - dzil cover -report coveralls

env: RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1
